/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoTenantRouteImport } from './routes/no-tenant'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAiInsightsIndexRouteImport } from './routes/_authenticated/ai-insights/index'
import { Route as AuthenticatedAuditLogIndexRouteImport } from './routes/_authenticated/audit-log/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events/create'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedIngestionIndexRouteImport } from './routes/_authenticated/ingestion/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedVolunteersIndexRouteImport } from './routes/_authenticated/volunteers/index'
import { Route as AuthenticatedVolunteersEmployeeIdRouteImport } from './routes/_authenticated/volunteers/$employeeId'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoTenantRoute = NoTenantRouteImport.update({
  id: '/no-tenant',
  path: '/no-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiInsightsIndexRoute =
  AuthenticatedAiInsightsIndexRouteImport.update({
    id: '/ai-insights/',
    path: '/ai-insights/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogIndexRoute =
  AuthenticatedAuditLogIndexRouteImport.update({
    id: '/audit-log/',
    path: '/audit-log/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngestionIndexRoute =
  AuthenticatedIngestionIndexRouteImport.update({
    id: '/ingestion/',
    path: '/ingestion/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVolunteersIndexRoute =
  AuthenticatedVolunteersIndexRouteImport.update({
    id: '/volunteers/',
    path: '/volunteers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVolunteersEmployeeIdRoute =
  AuthenticatedVolunteersEmployeeIdRouteImport.update({
    id: '/volunteers/$employeeId',
    path: '/volunteers/$employeeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/no-tenant': typeof NoTenantRoute
  '/select-tenant': typeof SelectTenantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/volunteers/$employeeId': typeof AuthenticatedVolunteersEmployeeIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/ai-insights/': typeof AuthenticatedAiInsightsIndexRoute
  '/audit-log/': typeof AuthenticatedAuditLogIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/ingestion/': typeof AuthenticatedIngestionIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/volunteers/': typeof AuthenticatedVolunteersIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/no-tenant': typeof NoTenantRoute
  '/select-tenant': typeof SelectTenantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/volunteers/$employeeId': typeof AuthenticatedVolunteersEmployeeIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ai-insights': typeof AuthenticatedAiInsightsIndexRoute
  '/audit-log': typeof AuthenticatedAuditLogIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/ingestion': typeof AuthenticatedIngestionIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/volunteers': typeof AuthenticatedVolunteersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/no-tenant': typeof NoTenantRoute
  '/select-tenant': typeof SelectTenantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/volunteers/$employeeId': typeof AuthenticatedVolunteersEmployeeIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ai-insights/': typeof AuthenticatedAiInsightsIndexRoute
  '/_authenticated/audit-log/': typeof AuthenticatedAuditLogIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/ingestion/': typeof AuthenticatedIngestionIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/volunteers/': typeof AuthenticatedVolunteersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/callback'
    | '/login'
    | '/no-tenant'
    | '/select-tenant'
    | '/dashboard'
    | '/events/$eventId'
    | '/events/create'
    | '/teams/$teamId'
    | '/volunteers/$employeeId'
    | '/admin/'
    | '/ai-insights/'
    | '/audit-log/'
    | '/events/'
    | '/feedback/'
    | '/ingestion/'
    | '/notifications/'
    | '/reports/'
    | '/teams/'
    | '/volunteers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/callback'
    | '/login'
    | '/no-tenant'
    | '/select-tenant'
    | '/dashboard'
    | '/'
    | '/events/$eventId'
    | '/events/create'
    | '/teams/$teamId'
    | '/volunteers/$employeeId'
    | '/admin'
    | '/ai-insights'
    | '/audit-log'
    | '/events'
    | '/feedback'
    | '/ingestion'
    | '/notifications'
    | '/reports'
    | '/teams'
    | '/volunteers'
  id:
    | '__root__'
    | '/404'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/no-tenant'
    | '/select-tenant'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/create'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/volunteers/$employeeId'
    | '/_authenticated/admin/'
    | '/_authenticated/ai-insights/'
    | '/_authenticated/audit-log/'
    | '/_authenticated/events/'
    | '/_authenticated/feedback/'
    | '/_authenticated/ingestion/'
    | '/_authenticated/notifications/'
    | '/_authenticated/reports/'
    | '/_authenticated/teams/'
    | '/_authenticated/volunteers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  NoTenantRoute: typeof NoTenantRoute
  SelectTenantRoute: typeof SelectTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-tenant': {
      id: '/no-tenant'
      path: '/no-tenant'
      fullPath: '/no-tenant'
      preLoaderRoute: typeof NoTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-insights/': {
      id: '/_authenticated/ai-insights/'
      path: '/ai-insights'
      fullPath: '/ai-insights/'
      preLoaderRoute: typeof AuthenticatedAiInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log/': {
      id: '/_authenticated/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuthenticatedAuditLogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingestion/': {
      id: '/_authenticated/ingestion/'
      path: '/ingestion'
      fullPath: '/ingestion/'
      preLoaderRoute: typeof AuthenticatedIngestionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volunteers/': {
      id: '/_authenticated/volunteers/'
      path: '/volunteers'
      fullPath: '/volunteers/'
      preLoaderRoute: typeof AuthenticatedVolunteersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volunteers/$employeeId': {
      id: '/_authenticated/volunteers/$employeeId'
      path: '/volunteers/$employeeId'
      fullPath: '/volunteers/$employeeId'
      preLoaderRoute: typeof AuthenticatedVolunteersEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedVolunteersEmployeeIdRoute: typeof AuthenticatedVolunteersEmployeeIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAiInsightsIndexRoute: typeof AuthenticatedAiInsightsIndexRoute
  AuthenticatedAuditLogIndexRoute: typeof AuthenticatedAuditLogIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedIngestionIndexRoute: typeof AuthenticatedIngestionIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedVolunteersIndexRoute: typeof AuthenticatedVolunteersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedVolunteersEmployeeIdRoute:
    AuthenticatedVolunteersEmployeeIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAiInsightsIndexRoute: AuthenticatedAiInsightsIndexRoute,
  AuthenticatedAuditLogIndexRoute: AuthenticatedAuditLogIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedIngestionIndexRoute: AuthenticatedIngestionIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedVolunteersIndexRoute: AuthenticatedVolunteersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  NoTenantRoute: NoTenantRoute,
  SelectTenantRoute: SelectTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
