server.port=8090
server.servlet.contextPath=/feedback-server

#spring.datasource.driverclassname=com.mysql.jdbc.Driver  
spring.datasource.url=jdbc:mysql://localhost:3306/outreachfeedbackdb?useSSL=false
spring.datasource.username=root
spring.datasource.password=pass@word1
#spring.jpa.generate-ddl=true

server.port=8090
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=visueng16@gmail.com
spring.mail.password=sristichauhan
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.suffix: .ftl