zuul:
  routes:
    feedback-server:
      path: /feedback-server/**
      serviceId: feedback-server
    report-server:
      path: /report-server/**
      serviceId: report-server 
     
ribbon:
  eureka:
    enabled: false
    
server:
  port: 7093
    